In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset=pd.read_csv('/CAR DETAILS FROM CAR DEKHO.csv')

In [ ]:
dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
dataset.shape

(4340, 8)

In [ ]:
dataset.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [ ]:
dataset.select_dtypes(include='object').columns

Index(['name', 'fuel', 'seller_type', 'transmission', 'owner'], dtype='object')

In [ ]:
dataset.select_dtypes(include='int').columns

Index(['year', 'selling_price', 'km_driven'], dtype='object')

In [ ]:
dataset.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [ ]:
dataset.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [ ]:
#add column
dataset["Current_year"]=2026

In [ ]:
dataset.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Current_year
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,2026
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,2026
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,2026
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,2026
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,2026

In [ ]:
dataset['old_year']=dataset["Current_year"]-dataset['year']

In [ ]:
dataset.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Current_year,old_year
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,2026,19
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,2026,19
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,2026,14
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,2026,9
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,2026,12

In [ ]:
dataset.head()

,selling_price,km_driven,fuel,seller_type,transmission,owner,old_year
0,60000,70000,Petrol,Individual,Manual,First Owner,19
1,135000,50000,Petrol,Individual,Manual,First Owner,19
2,600000,100000,Diesel,Individual,Manual,First Owner,14
3,250000,46000,Petrol,Individual,Manual,First Owner,9
4,450000,141000,Diesel,Individual,Manual,Second Owner,12

In [ ]:
dataset= pd.get_dummies(data=dataset,drop_first='object')

In [ ]:
dataset.head()

,selling_price,km_driven,old_year,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,60000,70000,19,False,False,False,True,True,False,True,False,False,False,False
1,135000,50000,19,False,False,False,True,True,False,True,False,False,False,False
2,600000,100000,14,True,False,False,False,True,False,True,False,False,False,False
3,250000,46000,9,False,False,False,True,True,False,True,False,False,False,False
4,450000,141000,12,True,False,False,False,True,False,True,False,True,False,False

In [ ]:
dataset

,selling_price,km_driven,old_year,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,60000,70000,19,False,False,False,True,True,False,True,False,False,False,False
1,135000,50000,19,False,False,False,True,True,False,True,False,False,False,False
2,600000,100000,14,True,False,False,False,True,False,True,False,False,False,False
3,250000,46000,9,False,False,False,True,True,False,True,False,False,False,False
4,450000,141000,12,True,False,False,False,True,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,409999,80000,12,True,False,False,False,True,False,True,False,True,False,False
4336,409999,80000,12,True,False,False,False,True,False,True,False,True,False,False
4337,110000,83000,17,False,False,False,True,True,False,True,False,True,False,False
4338,865000,90000,10,True,False,False,False,True,False,True,False,False,False,False
4339,225000,40000,10,False,False,False,True,True,False,True,False,False,False,False

In [ ]:
#matrix of features
x=dataset.drop(columns='selling_price')

In [ ]:
y=dataset['selling_price']

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [ ]:
x=scaler.fit_transform(x)
y = scaler.fit_transform(y.values.reshape(-1,1))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape

(3472, 13)

In [ ]:
y_train

array([[0.03153153],
       [0.06531532],
       [0.00844595],
       ...,
       [0.02815315],
       [0.06531532],
       [0.02364854]])

In [ ]:
x_test.shape

(868, 13)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.7290855319293978

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
print(mean_absolute_error(y_test, y_pred))

0.017722628153790512

In [ ]:
from sklearn.linear_model import Ridge, Lasso



lasso = Lasso(alpha=1.0)
lasso.fit(x_train, y_train)

Lasso()

In [ ]:
y_pred1 = lasso.predict(x_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred1)

print(mse)

0.004721306118620844

In [ ]:
mae = mean_absolute_error(y_test, y_pred1)

print(mae)

0.038880034581971624

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
params = {
    'n_estimators':[100,200,300,400,500,600,700,800,900,1000],

    'criterion':['squared_error','absolute_error'],

    'max_depth':[10,20,30,40,50],

    'min_samples_split':[2,5,10,20,50],

    'min_samples_leaf':[1,5,6,7],

    'max_features':['sqrt','log2']
}